server:
  port: 8082

spring:
  application:
    name: bff-mobile
  datasource:
    url: jdbc:mysql://localhost:3306/banco_xyz_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: MyDUOCSQL004!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

resilience4j:
  circuitbreaker:
    instances:
      notificacionMobileService:
        base-config: default
        sliding-window-size: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 8s
        register-health-indicator: true

