spring.application.name=auth-service
server.port=8084

# Importacion desde Spring Cloud Config Server (puerto 8888)
spring.config.import=optional:configserver:http://localhost:8888

# Eureka Discovery Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Configuracion JWT obtenida desde .env / Config Server
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:36000000}
