spring.application.name=batch-service

# Configuracion de conexion MySQL (Base de datos banco_xyz_db)
spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=MyDUOCSQL004!

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Configuracion Spring Batch 5
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true

# Permite seleccionar el Job via variable de entorno o argumento CLI:
# Opciones disponibles (compatibilidad con nombres tecnicos e informe EFT):
# 1. Transacciones Diarias : dailyTransaccionJob | procesarMovimientosJob
# 2. Calculo de Intereses  : monthlyInterestJob  | procesarInteresesJob
# 3. Estados Financieros   : annualStatementJob  | procesarEstadosFinancierosJob
spring.batch.job.name=${SPRING_BATCH_JOB_NAME:dailyTransaccionJob}

spring.main.web-application-type=none
spring.output.ansi.enabled=always
